[[test]]
hostname = "tohsa.ka"
path_begin = "/api" # optional
certificate = "assets/certificate.pem" # optional
key = "assets/key.pem" # optional
certificate_chain = "assets/certificate_chain.pem" # optional
frontends = ["HTTP", "HTTPS"] # list of proxy tags
backends  = ["127.0.0.1:1021"] # list of IP/port
sticky_session = false # optional, defaults to false

[[test]]
hostname  = "misa.ka"
frontends = ["HTTP"]
backends  = ["127.0.0.1:1022"]
sticky_session = true

[[other]]
hostname = "asu.ka"
path_begin = "/other"
frontends = ["HTTP"]
backends = ["127.0.0.1:1023"]
