[[magus]]
hostname = "tohsa.ka"
path_begin = "/api"
certificate = "assets/certs/certificate.pem"
key = "assets/certs/key.pem"
certificate_chain = "assets/certs/certificate_chain.pem"
frontends = ["HTTP", "HTTPS"]
backends  = ["127.0.0.1:1021"]
sticky_session = false

[[esper]]
hostname  = "misa.ka"
frontends = ["HTTP"]
backends  = ["127.0.0.1:1022"]
sticky_session = true

[[pilot]]
hostname = "asu.ka"
path_begin = "/other"
frontends = ["HTTP"]
backends = ["127.0.0.1:1023"]
