[[test]]
hostname = "tohsa.ka"
path_begin = "/api" # optional
certificate = "../sozu/lib/assets/certificate.pem" # optional
key = "../sozu/lib/assets/key.pem" # optional
certificate_chain = "../sozu/lib/assets/certificate_chain.pem" # optional
frontends = ["HTTP", "HTTPS"] # list of proxy tags
backends  = ["127.0.0.1:1021"] # list of IP/port
sticky_session = false

[[test]]
hostname  = "misa.ka"
frontends = ["HTTP"]
backends  = ["127.0.0.1:1022"]
sticky_session = true

[[other]]
hostname = "asu.ka"
path_begin = "/other"
frontends = ["HTTP"]
backends = ["127.0.0.1:1023"]
sticky_session = true
